# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdWkX-b9LM8cRp7rwLmkF7PcUlVP5Skc

**Module: Variables & Data Types**

Problem 1:  Declare five variables: your name (str), age (int), height in meters (float), whether you are a student (bool), and a variable with no value (NoneType). Print all five values in a single print() statement.

Approach:
I created variables of different data types (str, int, float, bool, NoneType) and printed them together using a single print() function.
"""

name = "Yasin"
age = 25
height = 1.70
is_student = True
nothing = None

print(name, age, height, is_student, nothing)

"""Problem 2:  Given x = '42', y = 3.9, z = True - convert x to int, y to int (notice what happens to the decimal), and z to str. Print each converted value and verify its type using type().

Approach:
I used Python's built-in type conversion functions (int(), str()) and verified the new data type using type().
"""

x = '42'
y = 3.9
z = True

x_int = int(x)
y_int = int(y)
z_str = str(z)

print(x_int, type(x_int))
print(y_int, type(y_int))
print(z_str, type(z_str))

"""Problem 3:  Assign the values 10, 20, 30 to three variables a, b, c in a single line. Then swap a and c without using a temporary variable and print both before and after values.

Approach: I assigned multiple values in one line using Python's multiple assignment feature. Then swaped the values of a and c directly using tuple unpacking.
"""

a, b, c = 10, 20, 30

print("Before Swap:")
print("a =", a, "b =", b, "c =", c)

a, c = c, a

print("After Swap:")
print("a =", a, "b =", b, "c =", c)

"""Problem 4:  Show dynamic typing in action: create a variable x, assign an integer to it and print its type, then reassign a string to the same variable and print its type again, then reassign a float and print once more.

Approach:
In this solution, Python is dynamically typed, meaning the same variable can hold different types of data at different times.
"""

x = 10
print(x, type(x))

x = "hello"
print(x, type(x))

x = 3.14
print(x, type(x))

"""Problem 5:  Try type-converting the following and print the result: bool(0), bool(''), bool('hello'), bool(99), int(True), int(False), float('3.14'). Write one conversion per line with a comment explaining the output.

Approach:
I applied various type Python's built-in conversion functions and observed how Python converts values into Boolean, integer, and floating-point data types.
"""

print(bool(0))        # False because 0 is falsy
print(bool(''))       # False because empty string is falsy
print(bool('hello'))  # True because non-empty string is truthy
print(bool(99))       # True because non-zero number is truthy

print(int(True))      # 1
print(int(False))     # 0

print(float('3.14'))  # 3.14

"""**Module: Basic Operators**

Problem 6:  Store any two integers in variables a and b. Print the result of all seven arithmetic operations (+, -, *, /, //, %, **) with a descriptive label for each line. Example: 'Floor division: 3'.

Approach:
I used two integer variables and performed all basic arithmetic operations with these operators -> +, -, *, /, //, %, **, then displayed each result with a descriptive label.
"""

a = 10
b = 3

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Power:", a ** b)

"""Problem 7:  Start with x = 100. Apply these augmented assignment operations in order and print x after each step: subtract 25, multiply by 2, floor-divide by 3, take modulus with 7, raise to power 2.

Approach:
I used augmented assignment operators like -=, *=, //=, %=, and **= to modify the variable step by step and printed the updated value after each operation.
"""

x = 100

x -= 25
print(x)

x *= 2
print(x)

x //= 3
print(x)

x %= 7
print(x)

x **= 2
print(x)

"""Problem 8:  Given a = 15, b = 15, c = [1,2], d = [1,2] - print the result of: a == b, a is b, c == d, c is d. Then explain in a comment why 'is' and '==' give different results for the lists.

Approach:
I Compared variables using both equality (==) and identity (is) operators to understand the difference between value comparison and object comparison.Here, '==' checks whether values are equal, while 'is' checks whether two variables refer to the same object in memory.
"""

a = 15
b = 15
c = [1, 2]
d = [1, 2]

print(a == b)
print(a is b)

print(c == d)
print(c is d)

# == compares values.
# is compares memory locations (object identity).

"""Problem 9:  Write expressions using logical operators to check: (1) a number is between 10 and 50 (inclusive), (2) a string is either 'yes' or 'no', (3) a number is NOT divisible by 2. Test each with sample values and print True/False.

Approach:
I created sample values, used logical operators to evaluate multiple conditions and displayed Boolean results.
"""

number = 25
print(10 <= number <= 50)

text = "yes"
print(text == "yes" or text == "no")

n = 7
print(not (n % 2 == 0))

"""Problem 10:  Check membership using 'in' and 'not in': (1) is 'py' inside 'python'? (2) is 'z' not in 'python'? (3) is 7 in the list [1, 3, 5, 7, 9]? (4) is 4 not in the same list? Print each result.

Approach:
I checked whether specific elements existed in strings and lists using the membership operators 'in' and 'not in' in print() function.
"""

print("py" in "python")

print("z" not in "python")

numbers = [1, 3, 5, 7, 9]

print(7 in numbers)

print(4 not in numbers)

"""**Module: String Manipulation**

Problem 11:  Take the string s = '  python programming  '. In separate print statements, show: the stripped version, stripped + upper(), stripped + title(), stripped + replace('python', 'data'), and the length of the stripped string.

Approach:
I firsty removed extra spaces from a string using strip(), then applied several string methods such as uppercase conversion, title case conversion, replacement, and length calculation.
"""

s = " python programming "

clean = s.strip()

print(clean)
print(clean.upper())
print(clean.title())
print(clean.replace("python", "data"))
print(len(clean))

"""Problem 12:  Given text = 'Data,Science,Machine,Learning' - split it into a list, print the list, print the second element, print the total number of elements, then join the list back with ' → ' as separator.

Approach:
I used split() function to split a comma-separated string into a list, accessed list elements, counted items, and joined the elements back into a string using join() function.
"""

text = "Data,Science,Machine,Learning"

items = text.split(",")

print(items)
print(items[1])
print(len(items))

print(" → ".join(items))

"""Problem 13:  Given sentence = 'Hello World Python' - use slicing to print: the first 5 characters, the last 6 characters, every second character, and the entire string reversed.

Approach:
I used Python string slicing techniques to extract different parts of the given string, such as the first characters, last characters, every second character, and the reversed string and displayed each version of the orginal text.
"""

sentence = "Hello World Python"

print(sentence[:5])

print(sentence[-6:])

print(sentence[::2])

print(sentence[::-1])

"""Problem 14:  For the string word = 'Banana' - print the result of: find('a'), count('a'), startswith('Ba'), endswith('na'), isdigit(). Then check if '12345'.isdigit() is different from '123a5'.isdigit().

Approach:
I used different string methods like find() to find a character,count() to count that character and check characters in the given string using startswith() and endswith().I also used 'isdigit()' to determine whether a string contains only numeric digits.
"""

word = "Banana"

print(word.find("a"))

print(word.count("a"))

print(word.startswith("Ba"))

print(word.endswith("na"))

print(word.isdigit())

print("12345".isdigit())

print("123a5".isdigit())

"""Problem 15:  Create three variables: product = 'Laptop', price = 75000.5, discount = 10. Print a formatted line using all three string formatting styles (f-string, .format(), % operator) showing: 'Product: Laptop | Price: 75000.50 | Discount: 10%'.

Approach:
I used three different string formatting methods : f-string, '.format()', and '%' formatting to display product information in a well-formatted and readable way. The price was formatted to show two decimal places.
"""

# Commented out IPython magic to ensure Python compatibility.
product = "Laptop"
price = 75000.5
discount = 10

print(f"Product: {product} | Price: {price:.2f} | Discount: {discount}%")

print(
    "Product: {} | Price: {:.2f} | Discount: {}%".format(
        product, price, discount
    )
)

print(
    "Product: %s | Price: %.2f | Discount: %d%%"
#     % (product, price, discount)
)

"""**Module: Input / Output**

Problem 16:  Write a program that takes the user's name and birth year as input. Calculate their approximate age (current year - birth year) and print: 'Hello [name]! You are approximately [age] years old.'

Approach:
I took the user's name and birth year as input, converted the birth year into an integer, calculated the approximate age by subtracting it from the current year, and displayed the result in a personalized message.
"""

name = input("Enter your name: ")

birth_year = int(input("Enter your birth year: "))

age = 2025 - birth_year

print(f"Hello {name}! You are approximately {age} years old.")

name = input("Enter your name: ")

birth_year = int(input("Enter your birth year: "))

age = 2025 - birth_year

print(f"Hello {name}! You are approximately {age} years old.")

"""Problem 17:  Build a simple area calculator. Ask the user to enter length and width (as floats). Calculate area and perimeter of the rectangle. Print both results formatted to 2 decimal places with descriptive labels.

Approach:
I took the length and width of a rectangle as input, calculated the area and perimeter using standard mathematical formulas, and displayed the results with two decimal places for better readability.
"""

length = float(input("Enter length: "))
width = float(input("Enter width: "))

area = length * width
perimeter = 2 * (length + width)

print(f"Area: {area:.2f}")
print(f"Perimeter: {perimeter:.2f}")

length = float(input("Enter length: "))
width = float(input("Enter width: "))

area = length * width
perimeter = 2 * (length + width)

print(f"Area: {area:.2f}")
print(f"Perimeter: {perimeter:.2f}")

"""**Module: Conditional Statements**

Problem 18:  Take a score (0 - 100) from the user and print a grade using if-elif-else: 90–100 → 'A+', 80–89 → 'A', 60–79 → 'B', 40–59 → 'C', below 40 → 'F'. Also print 'Pass' or 'Fail' based on score >= 40.

Approach:
I used an if-elif-else statement to determine the grade based on the student's score. Then, a separate condition was used to check whether the student passed or failed.
"""

score = int(input("Enter score: "))

if 90 <= score <= 100:
    grade = "A+"
elif 80 <= score <= 89:
    grade = "A"
elif 60 <= score <= 79:
    grade = "B"
elif 40 <= score <= 59:
    grade = "C"
else:
    grade = "F"

print("Grade:", grade)

if score >= 40:
    print("Pass")
else:
    print("Fail")

score = int(input("Enter score: "))

if 90 <= score <= 100:
    grade = "A+"
elif 80 <= score <= 89:
    grade = "A"
elif 60 <= score <= 79:
    grade = "B"
elif 40 <= score <= 59:
    grade = "C"
else:
    grade = "F"

print("Grade:", grade)

if score >= 40:
    print("Pass")
else:
    print("Fail")

"""Problem 19:  Write a login system. Store a correct username and password in two variables. Take username and password input from the user. Using nested if-else: if username matches → check password → print 'Access Granted' or 'Wrong Password'; if username doesn't match → print 'User Not Found'.

Approach:
I used nested if-else statements to create a simple login system. The program first checks the username, and if it is correct, it then checks the password to determine whether access should be granted.
"""

correct_username = "admin"
correct_password = "12345"

username = input("Enter username: ")
password = input("Enter password: ")

if username == correct_username:

    if password == correct_password:
        print("Access Granted")
    else:
        print("Wrong Password")

else:
    print("User Not Found")

correct_username = "admin"
correct_password = "12345"

username = input("Enter username: ")
password = input("Enter password: ")

if username == correct_username:

    if password == correct_password:
        print("Access Granted")
    else:
        print("Wrong Password")

else:
    print("User Not Found")

"""Problem 20:  Take any number from the user. Using a single line ternary expression, print whether it is 'Positive', 'Negative', or 'Zero'. Then separately, using nested if-elif-else, also check if the number is even or odd (only if it is not zero).

Approach:
I used a nested ternary expression to determine whether the entered number is positive, negative, or zero. Then, used conditional statements to check whether the number is even or odd if it is not zero.
"""

number = int(input("Enter a number: "))

result = (
    "Positive"
    if number > 0
    else ("Negative" if number < 0 else "Zero")
)

print(result)

if number != 0:

    if number % 2 == 0:
        print("Even")
    else:
        print("Odd")

else:
    print("Zero is neither even nor odd.")

number = int(input("Enter a number: "))

result = (
    "Positive"
    if number > 0
    else ("Negative" if number < 0 else "Zero")
)

print(result)

if number != 0:

    if number % 2 == 0:
        print("Even")
    else:
        print("Odd")

else:
    print("Zero is neither even nor odd.")